name: Build Test

run-name: Build GMSAPasswordReader

on:
  push:
    branches:
      - test

env:
  BUILD_SLN: ${{ github.workspace }}\GMSAPasswordReader\GMSAPasswordReader.sln

jobs:
  build:
    strategy:
      matrix:
        # Release | Debug
        CONFIGURATION: [Release]

    runs-on: windows-2019

    steps:
      - name: Clone Rubeus
        uses: actions/checkout@v3
        with:
          repository: rvazarkar/GMSAPasswordReader
          ref: master
          path: GMSAPasswordReader
      - run: |
          pwd
          ls

      - name: Install .Net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1
        # with:
        #   msbuild-architecture: x64

      - name: Restore the application
        # HACK: 使用 /t:restore 否则报错
        # This project references NuGet package(s) that are missing on this computer. 
        # Use NuGet Package Restore to download them.
        # msbuild ${{ github.workspace }}\GMSAPasswordReader\GMSAPasswordReader.sln /t:restore /p:RestorePackagesConfig=true
        # msbuild ${{ github.workspace }}\GMSAPasswordReader\GMSAPasswordReader.sln /p:Configuration=$env:Configuration /p:Platform="Any CPU"
        run: |
          msbuild $env:BUILD_SLN /t:restore,build /p:RestorePackagesConfig=true /p:Configuration=$env:Configuration /p:Platform="Any CPU"
        env:
          Configuration: ${{ matrix.CONFIGURATION }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GMSAPasswordReader
          path: ${{ github.workspace }}