name: Build GMSAPasswordReader

run-name: GMSAPasswordReader

on:
  push:
    branches:
      - GMSAPasswordReader

jobs:
  build:
    strategy:
      matrix:
        # Release | Debug
        CONFIGURATION: [Release]

    runs-on: windows-2019

    steps:
      - name: Clone GMSAPasswordReader
        uses: actions/checkout@v3
        with:
          repository: rvazarkar/GMSAPasswordReader
          ref: master
          path: GMSAPasswordReader
      - run: |
          pwd
          ls

      - name: Install .Net Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Restore the application
        run: |
          msbuild /p:Configuration=$env:Configuration /p:Platform="Any CPU" ${{ github.workspace }}\GMSAPasswordReader\GMSAPasswordReader.sln
        env:
          Configuration: ${{ matrix.CONFIGURATION }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GMSAPasswordReader
          path: ${{ github.workspace }}
